
source 'https://github.com/CocoaPods/Specs.git'		#官方仓库地址
source 'https://github.com/gakaki/gakakiPods.git'		#私有仓库地址

platform :ios, '9.0'

project './MainProject.xcodeproj'

target 'MainProject' do
  use_frameworks!

  # pod 'CommonLib'
  pod 'ModuleMainPage', :path => '../ModuleMainPage'
  
end


